### ISSUE TITLE
Otra pregunta de ejemplo

### ISSUE THREAD

**Issue by ghost** [glantucan/puzzle_game#2]
Supercalifragilísticoespiralidoso

**Comment by glantucan** [comment]
fsdñlfksad ñfsdf

**Comment by glantucan** [comment]
aaslkdj **alks** 
[puzzle_game.zip](https://github.com/glantucan/puzzle_game/files/547363/puzzle_game.zip)

j cñkjh sdñklfh asldkjvh adsñklv asdñlkvj asñlkdvj aklf vñj lkj ?

``` cs
void PerformAction(string buttonName, bool isButtonActive){
        string targetSuffix =  this.GetTargetNameSuffix(buttonName);
        string targetName = "Animated" + targetSuffix;
        GameObject target = GameObject.Find(targetName);
        Animation targetAnimation = target.GetComponent<Animation>();
        if (isButtonActive) {
            targetAnimation.Play("hide" + targetSuffix);
        } else {
            targetAnimation.Play("show" + targetSuffix);
        }
    }
```

**Comment by alijahanmard** [comment]
Hola! 
Intento hacer el ejercicio 19, y tengo problema con normalizar el vector para que la velocidad que defino no afecte a la magnitud del vector. 

``` c#
public class Script_19 : MonoBehaviour {

    public float v ;
    private Vector3 direction;  
    public Vector3 pasaPosition;

    // Use this for initialization
    void Start () {


    }

    // Update is called once per frame
    void Update () {
        this.direction = (this.pasaPosition - this.transform.position);
        Vector3 velocity = (v * direction) * Time.deltaTime;
        this.transform.position = velocity + this.transform.position;

    }
}
```

Ahora mismo con este codigo funciona bien pero el objeto se para al llegar a las cordenadas de "pasaPosition". 
para normalizar la direccion lo  que se me ocurre es añadir:
        `this.direction = this.direction.normalized;`
no me da error, pero tampoco soluciona el problema. 
igual me estoy equivocando en todo xD. 

Gracias.
