### ISSUE TITLE
Duda - Cómo obtener el valor de una propiedad privada de un script desde otro script diferente 

### ISSUE THREAD

**Issue by JorgeHurtado** [glantucan/puzzle_game#8]
Hola, haciendo el ejercicio 26 me he encontrado con un problema: 

Tenía que acceder al valor de una propiedad de un script desde otro script distinto. La variable es **velocidadVectorial**, definida en el script **Vectores25_1**. Queria poder obtener su valor y modificarlo desde el script **Vectores26**. Al ser una propiedad definida como privada, me sale un error en el código

![error](https://cloud.githubusercontent.com/assets/23083408/19823753/af177f10-9d6a-11e6-8686-11e1b1f18ffa.JPG)

```

public class Vectores25_1: MonoBehaviour {
    private Vector3 velocidadVectorial;
    private Vector3 destinoPosition;
           ...
```

```
public class Vectores26: MonoBehaviour {
    public GameObject sphere;
    private float v;
    private Vector3 velocidadVectorial;
    private Vector3 destinoPosition;
    private Vector3 direction;

    // Use this for initialization
    void Start () {
    }

    // Update is called once per frame
    void Update () {
        this.destinoPosition = sphere.transform.position;
        this.direction = (this.destinoPosition - this.transform.position).normalized;
        this.v = sphere.GetComponent<Vectores25_1>().velocidadVectorial.magnitude;
        this.velocidadVectorial = this.direction * this.v;
                ...
```

Se que el problema está en el private, cambiando la propiedad **velocidadVectorial** a public (que para la entrega de la actividad es lo que he hecho) todo funcionaría perfecto, pero esto implica que cualquiera desde el inspector puede cambiar la propiedad sin darse cuenta. ¿Hay alguna forma de acceder a esta variable privada o de esconder en el inspector la variable publica para que no se le pueda poner valores?

**EDIT:** Te he cambiado el nombre del hilo porque en ralidad to código no intenta modificar el valor de la propiedad  `velocidadVectorial` de Vectores25_1, sólo la _lee_. Si no te he entendido bien y quieres cambiarlo, y añadir algún comentario al respecto, hazlo, por favor.

**Comment by glantucan** [comment]
Sí, no lo hemos visto de forma explícita todavía, pero sí que lo hemos comentado un par de veces. 

La idea es, como os conté, que las propiedades sean siempre privadas y que si se quiere acceder a su valor desde otro script se cree una función pública que lo devuelva:
Así en tu clase `Vectores25_1` tendrías que tener algo así:

``` cs
public class Vectores25_1: MonoBehaviour {
    private Vector3 velocidadVectorial;
    //...
    public Vector3 GetVelocity() {
        return this.velocidadVectorial;
    }
    //...
```

Y en Vectores26 algo así:

``` cs
public class Vectores26: MonoBehaviour {
    public GameObject sphere;
    private float v;
    void Update () {
        //...
        Vector3 Vectores25_1 targetMovementControl = sphere.GetComponent<Vectores25_1>();
        this.v =targetMovementControl.GetVelocity().magnitude;
        this.velocidadVectorial = this.direction * this.v;
        //...
    }
```

Hay varios motivos por los que merece la pena dar este rodeo (creando una función pública en lugar de poner la propiedad como pública).
- Si por cualquier motivo decides cambiar el nombre o el tipo de la propiedad `velocidadVectorial` o prescindir de ella porque cambias el modo de hacer los cálculos en Vectores 25_1 Todos los cambios quedan dentro de esa clase. Sólo tendrías cambiar el código del método `GetVelocity()`, que está en la misma clase para que cualquier otra clase que lo llame siguiera funcionando correctamente. Si usaras directamente una propiedad pública tendrías que ir a cambiar, en todas las clases que la usen, ese código.
- Por otro lado, ese rodeo, nos obliga a pensar dos veces si realmente queremos compartir esa información con el exterior. En general hay que intentar mantener las dependencias entre clases al mínimo, para que sean lo más reutilizables que sea posible. Si hay muchas clases que dependan de otras, eso es muy difícil.

Fíjate en que he añadido una variable intermedia `targetMovementControl` para que quede más claro lo que estoy haciendo. Además, es mejor hacerlo así porque en un momento dado podríamos querer obtener más información (llamando a otras posibles funciones) de la instancia de Vectores25_1 que controla el movimiento de el gameobject perseguido.

**Comment by glantucan** [comment]
Enlazando con la primera razón por la que es mejor usar una función para obtener un valor desde otra clase. En tu caso se puede evitar que si lo que quieres obtener la magnitud de la velocidad de la instancia de Vectores25_1, haya que usar `magnitude` después de obtener la velocidad vectorial y todo gracias a que es una función, y no un variable, lo que _"exportas"_:

``` cs
public class Vectores25_1: MonoBehaviour {
    private Vector3 velocidadVectorial;
    //...
    public float GetVelocity() {
        return this.velocidadVectorial.magnitude;
    }
```

Así te ahorrarías el cálculo en Vectores26 y tu código en esa clase queda más sencillo.

``` cs
public class Vectores26: MonoBehaviour {
    public GameObject sphere;
    private float v;
    void Update () {
        //...
        Vector3 Vectores25_1 targetMovementControl = sphere.GetComponent<Vectores25_1>();
        this.velocidadVectorial = this.direction * targetMovementControl.GetVelocity();
        //...
```

**Comment by JorgeHurtado** [comment]
Vale, muchas gracias, de esta forma si que podría obtener el valor y usarlo sin problemas, pero me surge otra pregunta:

Si en vez de obtener el valor y usarlo sin más, quiero **modificarlo** (En el ejercicio 27 la tengo que cambiar), ¿Tendría que  escribir una funcion **Set** a la que le paso un parámetro? Por ejemplo para que la velocidad sea 0 cuando pasan 200 frames, ¿Sería asi?

```
public class Vectores25_1: MonoBehaviour {
    private Vector3 velocidadVectorial;
    //...
    public float GetVelocity() {
        return this.velocidadVectorial.magnitude;
    }
    public void SetVelocity(Vector3 newVelocity){
       this.velocidadVectorial = newVelocity;
    }
```

```
public class Vectores26: MonoBehaviour {
    public GameObject sphere;
    private float v;
    private velocidadVectorial;
    private direction;
    void Update () {
        //...
        Vector3 Vectores25_1 targetMovementControl = sphere.GetComponent<Vectores25_1>();
        this.velocidadVectorial = this.direction * targetMovementControl.GetVelocity();
       if(Time.frameCount>200){
             targetMovementControl.SetVelocity(Vector3.zero);
        }
        //...
```

En unity esto me funciona, pregunto por saber si es correcto hacerlo así o hay alguna otra forma de hacerlo ahorrándome la función **SetVelocity**.

**Comment by glantucan** [comment]
Es correcto. Hay otras formas de hacerlo, pero no suponen una diferencia
significativa.

**Comment by JorgeHurtado** [comment]
Vale, gracias.

**Comment by glantucan** [comment]
De nada :)
No cerreis los hilos, porque dejan de ser visibles en la página principal del foro. La idea es que queden abiertos para que cualquiera pueda encontrarlos y leerlos fácilmente.
